export enum ModalTypes {
    STORY = 'STORY',
    TEAM = 'TEAM',
    PROJECT = 'PROJECT',
    EPIC = 'EPIC',
    SPRINT = 'SPRINT',
    USER_CUSTOMER = 'USER_CUSTOMER',
    USER_SELF = 'USER_SELF',
    WORKSPACE = 'WORKSPACE',
}

export enum ModalOptions {
    WORKSPACE_UPDATE = 'WORKSPACE_UPDATE',
    TEAM_UPDATE = 'TEAM_UPDATE',
    USER_CREATION = 'USER_CREATION',
    EPIC_UPDATE = 'EPIC_UPDATE',
    CUSTOMER_CREATION = 'CUSTOMER_CREATION',
}
