export enum ModalTypes {
    STORY = 'STORY',
    TEAM = 'TEAM',
    PROJECT = 'PROJECT',
    EPIC = 'EPIC',
    SPRINT = 'SPRINT',
    USER_CUSTOMER = 'USER_CUSTOMER',
    USER_SELF = 'USER_SELF',
    WORKSPACE = 'WORKSPACE',
}

export enum ModalOptions {
    CUSTOMER_CREATION = 'CUSTOMER_CREATION',
    WORKSPACE_UPDATE = 'WORKSPACE_UPDATE',
    TEAM_UPDATE = 'TEAM_UPDATE',
    EPIC_UPDATE = 'EPIC_UPDATE',
    SPRINT_UPDATE = 'SPRINT_UPDATE',
    PROJECT_UPDATE = 'PROJECT_UPDATE',
    EPIC_REMOVE = 'EPIC_REMOVE',
    SPRINT_REMOVE = 'SPRINT_REMOVE',
    PROJECT_REMOVE = 'PROJECT_REMOVE',
}
